image: php:8.0-fpm

variables:
  MYSQL_DATABASE: "singularity"
  MYSQL_ROOT_PASSWORD: "dbpass"
  MYSQL_USER: "singularity"
  MYSQL_PASSWORD: "R&4*h223b5yP"
  MYSQL_HOST: mysql

services:
  - mysql:latest

stages:
  - deploy

before_script:
  - apt-get update
  - apt-get install -y nginx
  - service nginx start
  - apt-get update && apt-get install -y git curl libmcrypt-dev default-mysql-client
  - mysql --version
  - sleep 10
  - echo "SHOW tables;" | mysql -u root -p"$MYSQL_ROOT_PASSWORD" -h "${MYSQL_HOST}" "${MYSQL_DATABASE}"
  - echo "Database host is '${MYSQL_HOST}'"

deploy:
  stage: deploy
  script:
    - deployer dyno replace frontend $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG gitlab-ci-token $REGISTRY_PWD
  only:
    - master
