image: php:8.0-fpm

services:
  - mysql:5.7

stages:
  - deploy

before_script:
  - apt-get update
  - apt-get install -y nginx
  - service nginx start
  - apt update
  - apt-get install -y mysql-client
  - mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD -e "CREATE USER 'singularity'@'%' IDENTIFIED BY 'R&4*h223b5yP';"
  - mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD -e "CREATE DATABASE singularity;"
  - mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD -e "GRANT ALL PRIVILEGES ON singularity.* TO 'singularity'@'%';"
  - mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD singularity < db.sql

deploy:
  stage: deploy
  script:
    - deployer dyno replace frontend $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG gitlab-ci-token $REGISTRY_PWD
  only:
    - master
