image: registry.secoder.net/tool/deployer

services:
  - mysql:latest
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  only:
    - master

unit-test:
  image: php:8.1-apache
  stage: test
  before_script:
    - apt-get update -yqq
    - apt-get install git -yqq
    - curl --location --output /usr/local/bin/phpunit "https://phar.phpunit.de/phpunit.phar"
    - chmod +x /usr/local/bin/phpunit
    - docker-php-ext-install mysqli pdo pdo_mysql
    - pecl install pcov && docker-php-ext-enable pcov
  script:
    - phpunit --configuration phpunit.xml --coverage-xml=coverage.xml --log-junit=execution-result.xml
  after_script:
    - SUFFIX=$RANDOM
    - curl "http://api.secoder.net/static/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz" -C /opt
    - /opt/sonar-scanner/bin/sonar-scanner

deploy:
  stage: deploy
  script:
    deployer dyno replace $CI_PROJECT_NAME $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $REGISTRY_USER $REGISTRY_PWD
  only:
    - master
