image: registry.secoder.net/tool/deployer

variables:
  MYSQL_DATABASE: "singularity"
  MYSQL_ROOT_PASSWORD: "dbpass"
  MYSQL_USER: "singularity"
  MYSQL_PASSWORD: "R&4*h223b5yP"
  MYSQL_HOST: mysql

services:
  - mysql:latest

stages:
  - deploy


deploy:
  stage: deploy
  script:
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - apt-get update
    - apt-get install -y nginx
    - service nginx start
    - apt-get update && apt-get install -y git curl libmcrypt-dev default-mysql-client
    - mysql -h mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < singularity.sql
    - mysql -h mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e "SHOW TABLES;"
    - deployer build
  only:
    - master
