image: php:8.0-fpm

variables:
  MYSQL_DATABASE: "singularity"
  MYSQL_ROOT_PASSWORD: "dbpass"
  MYSQL_USER: "singularity"
  MYSQL_PASSWORD: "R&4*h223b5yP"
  MYSQL_HOST: mysql

services:
  - mysql:latest

stages:
  - deploy

before_script:
  - apt-get update
  - apt-get install -y nginx
  - service nginx start
  - apt-get update && apt-get install -y git curl libmcrypt-dev default-mysql-client
  - mysql --version
  - systemctl start mysql
  - sleep 3
  - mysql -h localhost -u ${DB_USER} -p"${DB_PASSWORD}" -e "CREATE DATABASE singularity;"
  - mysql -h localhost -u ${DB_USER} -p"${DB_PASSWORD}" -e "CREATE USER 'singularity'@'%' IDENTIFIED BY 'R&4*h223b5yP';"
  - mysql -h localhost -u ${DB_USER} -p"${DB_PASSWORD}" -e "GRANT ALL PRIVILEGES ON singularity.* TO 'singularity'@'%';"


deploy:
  stage: deploy
  script:
    - deployer dyno replace frontend $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG gitlab-ci-token $REGISTRY_PWD
  only:
    - master
