image: registry.secoder.net/tool/deployer

variables:
  MYSQL_DATABASE: "singularity"
  MYSQL_ROOT_PASSWORD: "dbpass"
  MYSQL_USER: "singularity"
  MYSQL_PASSWORD: "R&4*h223b5yP"
  MYSQL_HOST: mysql

services:
  - mysql:latest

stages:
  - deploy


deploy:
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y nginx
    - service nginx start
    - apt-get update && apt-get install -y git curl libmcrypt-dev default-mysql-client
    - mysql -h mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < singularity.sql
    - mysql -h mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e "SHOW TABLES;"
    - deployer dyno replace frontend $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG gitlab-ci-token $REGISTRY_PWD
  only:
    - master
